# Generated by Django 3.2.4 on 2021-07-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=70, verbose_name='Имя автора')),
                ('describe_author', models.TextField(max_length=300, verbose_name='Описание автора')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photo_author', verbose_name='Фото автора')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=70, verbose_name='Название книги')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('book_describe', models.TextField(max_length=300, verbose_name='Описание книги')),
                ('book_state', models.CharField(choices=[('Отличное', 'Отличное'), ('Хорошее', 'Хорошее'), ('Среднее', 'Среднее'), ('Плохое', 'Плохое')], default='хорошее', max_length=50, verbose_name='Состояние книги')),
                ('exchange_status', models.BooleanField(default=False, verbose_name='Статус готовности обмена книги')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_book', to='books.book', verbose_name='Книга')),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Image_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_book', models.ImageField(blank=True, null=True, upload_to='image_book', verbose_name='Изображение книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_book', to='books.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200, verbose_name='Название коментария')),
                ('comment_text', models.TextField(max_length=4000, verbose_name='Текст коментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан коментарий')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_book', to='books.book', verbose_name='Книга')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец книги'),
        ),
    ]
