# Generated by Django 3.2.4 on 2021-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
    ]
