# Generated by Django 3.2.4 on 2021-06-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=70, verbose_name='Изображение книги')),
                ('describe_author', models.TextField(max_length=300)),
                ('photo_author', models.ImageField(upload_to='photo_author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=70, verbose_name='Название книги')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('book_describe', models.TextField(max_length=300, verbose_name='Описание книги')),
                ('book_state', models.CharField(choices=[('Отличное', 'Отличное'), ('Хорошее', 'Хорошее'), ('Среднее', 'Среднее'), ('Плохое', 'Плохое')], default='хорошее', max_length=50, verbose_name='Состояние книги')),
                ('exchange_status', models.BooleanField(default=False, verbose_name='Статус готовности обмена книги')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.book')),
            ],
            options={
                'verbose_name': 'Рейтинг книги',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Image_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_book', models.ImageField(upload_to='image_book', verbose_name='Изображение книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200)),
                ('comment_text', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.book')),
            ],
        ),
    ]
