# Generated by Django 3.2.4 on 2021-06-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='username',
        ),
    ]
