# Generated by Django 3.2.4 on 2021-06-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_alter_book_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='username',
            new_name='user',
        ),
    ]
