# Generated by Django 3.2.4 on 2021-06-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_rename_username_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_book', to='exchange.book', verbose_name='Книга'),
        ),
    ]
