# Generated by Django 3.2.4 on 2021-06-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_alter_comment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_book', to='exchange.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='image_book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='image_book', verbose_name='Изображение книги'),
        ),
    ]
